apps/crud/models.py
from datetime import datetime

from apps.app import db
from werkzeug.security import generate_password_hash


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    @property
    def password(self):
        raise AttributeError("読み取り不可")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


class UserForm(FlaskForm):
    username = StringField(
        "ユーザー名",
        validators=[
            DataRequired(message="ユーザー名は必須です。"),
            length(max=30, message="30文字以内で入力してください。"),
        ],
    )

    email = StringField(
        "メールアドレス",
        validators=[
            DataRequired(message="メールアドレスは必須です。"),
            Email(message="メールアドレスの形式で入力してください。"),
        ],
    )

    password = PasswordField("パスワード", validators=[DataRequired(message="パスワードは必須です。")])

    submit = SubmitField("新規登録")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from apps.app import db
from apps.crud.forms import UserForm
from apps.crud.models import User
from flask import Blueprint, redirect, render_template, url_for

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@crud.route("/")
def index():
    return render_template("crud/index.html")


@crud.route("/sql")
def sql():
    db.session.query(User).all()
    return "コンソールログを確認してください"


@crud.route("/users/new", methods=["GET", "POST"])
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


@crud.route("/users")
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>ユーザー新規作成</title>
</head>

<body>
    <h2>ユーザー新規作成</h2>
    <form action="{{ url_for('crud.create_user') }}" method="POST" novalidate="novalidate">
        {{ form.csrf_token }}
        <p>
            {{ form.username.label }} {{ form.username(placeholder="ユーザ名") }}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}
        </p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>{{ form.submit() }}</p>
    </form>
</body>

</html>

apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>ユーザーの一覧</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}" />
</head>

<body>
    <h2>ユーザーの一覧</h2>

    <a href="{{ url_for('crud.create_user') }}">ユーザー新規作成</a>

    <table>
        <tr>
            <th>ユーザー</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
        </tr>
        {% for user in users %}
        <tr>
            <th>{{ user.id }}</th>
            <th>{{ user.username }}</th>
            <th>{{ user.email }}</th>
        </tr>
        {% endfor %}
    </table>
</body>

</html>